### ISSUE TITLE
Update anaconda link in deep learning setup.md

### ISSUE THREAD

**Issue by liekelotte** [esciencecenter-digital-skills/workshop-metadata#22]
@dsmits @dafnevk can one of you include the correct link?

**Comment by svenvanderburg** [comment]
@liekelotte which links need to be updated? The only thing I can see is this: https://github.com/carpentries-incubator/deep-learning-intro/issues/246 and will be fixed in setup instructions at the lesson material side. Can I close the issue?

**Comment by svenvanderburg** [comment]
Closed with https://github.com/carpentries-incubator/deep-learning-intro/issues/246
