### ISSUE TITLE
add `title.md` to metadata

### ISSUE THREAD

**Issue by mkuzak** [esciencecenter-digital-skills/workshop-metadata#7]
@liekelotte and I realised we do not have a place for the workshop title
We propose to include, for each workshop, a `title.md` file with the workshop title.
@SarahAlidoost  could you add this to the documentation for the metadata repository?

**Comment by SarahAlidoost** [comment]
@mkuzak please see the pull request https://github.com/esciencecenter-digital-skills/workshop-metadata/pull/10
