### ISSUE TITLE
`who.md` should include prerequisite knowledge

### ISSUE THREAD

**Issue by mkuzak** [esciencecenter-digital-skills/workshop-metadata#8]
it should only include expected prior knowledge, it should not include information about who are the participants (i.e PhD candidates). It is confusing, because this file is called `who` ,  so maybe we need to rename the file.

**Comment by SarahAlidoost** [comment]
@mkuzak to fix this issue, please see the pull request https://github.com/esciencecenter-digital-skills/workshop-metadata/pull/12
