### ISSUE TITLE
Update advertisement text of the Image Processing with Python

### ISSUE THREAD

**Issue by Sachavb** [esciencecenter-digital-skills/workshop-metadata#88]
Based on feedback from Joris we need to make the following changes.

> Did you know you can write your own programs and scripts to examine and manipulate images? Image processing is critical to many disciplines, ranging from health and biology to art history and astronomy. With code you can do your work in a much more efficient manner, whether you need to count bacteria on a plate, find pulmonary nodules in patient lungs or examine trends over time in museum catalogues. Join us for an in-depth look at images!

**Comment by drcandacemakedamoore** [comment]
Looks fine to me.

**Comment by svenvanderburg** [comment]
@drcandacemakedamoore can you submit a pull request with the changes?
