### ISSUE TITLE
changing the wording of the gpu programming sysnopsis

### ISSUE THREAD

**Issue by mkuzak** [esciencecenter-digital-skills/workshop-metadata#9]
Currently, it states: "This workshop introduces the fundamental knowledge needed to start programming GPUs using Python and CUDA." Introducing fundamental knowledge sounds to me like a lecture in theory. Our workshops focus on practice and hands-on experience. @isazi  @HannoSpreeuw can you think of rewording it to reflect the difference?

**Comment by HannoSpreeuw** [comment]
You are touching on a concern raised by our colleague Ben wrt the GPU programming course: that we merely teach students tricks to run code on GPUs without a firm understanding of what they are actually doing and in that way not using the full compute power of the GPU. So we definitely need to cover fundamental knowledge about the GPU and if that requires a lecture so be it. However, I think we do not need a lecture, a couple of slides will suffice.

**Comment by isazi** [comment]
I disagree @mkuzak , I think that this "This workshop introduces the fundamental knowledge needed to start programming GPUs using Python and CUDA." is what we aim for: giving students a view of some basic concepts. We do not have the time to teach a full GPU course, so we just give them something that, if they want, it can be used to learn on their own after our course is done.

**Comment by mkuzak** [comment]
@HannoSpreeuw  @isazi I'm not suggesting that we should change the content of the workshop. What I'm saying is that to me "introduce fundamental knowledge" sounds like this is a lecture, not a hands-on workshop. This workshop has both some theory and some practice with GPU code. I think this should be reflected in the short summary.

**Comment by HannoSpreeuw** [comment]
To me that phrase does not sound like a lecture.

**Comment by isazi** [comment]
We can have a brainstorming about that in the next co-working day and decide.

**Comment by SarahAlidoost** [comment]
Hi, may I suggest some templates to re-phrase the GPU synopsis? I might miss some points, please feel free to ignore/edit my comment. Perhaps, we can also pick the best and add as an example to [synopsis.md template](https://github.com/esciencecenter-digital-skills/workshop-metadata/blob/main/next-lesson/synopsis.md#example) later.

- This hands-on workshop will cover basic concepts and tools needed for GPUs programming using Python and CUDA.
- This workshop aims at teaching skills for GPUs programming. It is a hands-on training that covers basic concepts and tools using Python and CUDA. 
- This workshop introduces some concepts in the fundamentals of GPUs and teaches skills needed for GPUs programming using Python and CUDA.
- The aim of this workshop is to give attendees a view of some basics of GPUs and to teach skills needed for GPUs programming using Python and CUDA.

**Comment by svenvanderburg** [comment]
@SarahAlidoost, @isazi what did you decide? Can you update the synopsis based on that? Or can we close the issue in the meantime?

**Comment by HannoSpreeuw** [comment]
@SarahAlidoost All four come pretty close. I like the last one best, but the differences are minor.

**Comment by isazi** [comment]
This workshop covers the basic concepts and tools needed to program GPUs using Python and CUDA.
