### ISSUE TITLE
Update needed in course description for ds-cr

### ISSUE THREAD

**Issue by bvreede** [esciencecenter-digital-skills/workshop-metadata#94]
The name of the course suggests somewhat generally applicable contents, but it is actually quite Python oriented: while the main themes that are addressed are generically applicable, a lot of the exercises are in Python, as well as some demos and other practical applications. It would be useful to point this out in the course description.

**Comment by FenneRiemslagh** [comment]
Comment by me and @JaroCamphuijsen: There is a mention of basic python knowledge in the "who" section of the workshop metadata. I now also adjusted the description.md
